#ifndef __ADCVAL_CALC_H_
#define __ADCVAL_CALC_H_

	#ifdef NtcOnBoardResPullType

		#if ((NtcOnBoardResPullType==NtcOnBoardResPullUp))

			#define NtcAdcVal_at0	(TableValueType)((NtcAdcMaxVal*NtcResVal_at0  )/(NtcResVal_at0  +NtcOnBoardResVal))
			#define NtcAdcVal_at1	(TableValueType)((NtcAdcMaxVal*NtcResVal_at1  )/(NtcResVal_at1  +NtcOnBoardResVal))
			#define NtcAdcVal_at2	(TableValueType)((NtcAdcMaxVal*NtcResVal_at2  )/(NtcResVal_at2  +NtcOnBoardResVal))
			#define NtcAdcVal_at3	(TableValueType)((NtcAdcMaxVal*NtcResVal_at3  )/(NtcResVal_at3  +NtcOnBoardResVal))
			#define NtcAdcVal_at4	(TableValueType)((NtcAdcMaxVal*NtcResVal_at4  )/(NtcResVal_at4  +NtcOnBoardResVal))
			#define NtcAdcVal_at5	(TableValueType)((NtcAdcMaxVal*NtcResVal_at5  )/(NtcResVal_at5  +NtcOnBoardResVal))
			#define NtcAdcVal_at6	(TableValueType)((NtcAdcMaxVal*NtcResVal_at6  )/(NtcResVal_at6  +NtcOnBoardResVal))
			#define NtcAdcVal_at7	(TableValueType)((NtcAdcMaxVal*NtcResVal_at7  )/(NtcResVal_at7  +NtcOnBoardResVal))
			#define NtcAdcVal_at8	(TableValueType)((NtcAdcMaxVal*NtcResVal_at8  )/(NtcResVal_at8  +NtcOnBoardResVal))
			#define NtcAdcVal_at9	(TableValueType)((NtcAdcMaxVal*NtcResVal_at9  )/(NtcResVal_at9  +NtcOnBoardResVal))
			#define NtcAdcVal_at10	(TableValueType)((NtcAdcMaxVal*NtcResVal_at10 )/(NtcResVal_at10 +NtcOnBoardResVal))
			#define NtcAdcVal_at11	(TableValueType)((NtcAdcMaxVal*NtcResVal_at11 )/(NtcResVal_at11 +NtcOnBoardResVal))
			#define NtcAdcVal_at12	(TableValueType)((NtcAdcMaxVal*NtcResVal_at12 )/(NtcResVal_at12 +NtcOnBoardResVal))
			#define NtcAdcVal_at13	(TableValueType)((NtcAdcMaxVal*NtcResVal_at13 )/(NtcResVal_at13 +NtcOnBoardResVal))
			#define NtcAdcVal_at14	(TableValueType)((NtcAdcMaxVal*NtcResVal_at14 )/(NtcResVal_at14 +NtcOnBoardResVal))
			#define NtcAdcVal_at15	(TableValueType)((NtcAdcMaxVal*NtcResVal_at15 )/(NtcResVal_at15 +NtcOnBoardResVal))
			#define NtcAdcVal_at16	(TableValueType)((NtcAdcMaxVal*NtcResVal_at16 )/(NtcResVal_at16 +NtcOnBoardResVal))
			#define NtcAdcVal_at17	(TableValueType)((NtcAdcMaxVal*NtcResVal_at17 )/(NtcResVal_at17 +NtcOnBoardResVal))
			#define NtcAdcVal_at18	(TableValueType)((NtcAdcMaxVal*NtcResVal_at18 )/(NtcResVal_at18 +NtcOnBoardResVal))
			#define NtcAdcVal_at19	(TableValueType)((NtcAdcMaxVal*NtcResVal_at19 )/(NtcResVal_at19 +NtcOnBoardResVal))
			#define NtcAdcVal_at20	(TableValueType)((NtcAdcMaxVal*NtcResVal_at20 )/(NtcResVal_at20 +NtcOnBoardResVal))
			#define NtcAdcVal_at21	(TableValueType)((NtcAdcMaxVal*NtcResVal_at21 )/(NtcResVal_at21 +NtcOnBoardResVal))
			#define NtcAdcVal_at22	(TableValueType)((NtcAdcMaxVal*NtcResVal_at22 )/(NtcResVal_at22 +NtcOnBoardResVal))
			#define NtcAdcVal_at23	(TableValueType)((NtcAdcMaxVal*NtcResVal_at23 )/(NtcResVal_at23 +NtcOnBoardResVal))
			#define NtcAdcVal_at24	(TableValueType)((NtcAdcMaxVal*NtcResVal_at24 )/(NtcResVal_at24 +NtcOnBoardResVal))
			#define NtcAdcVal_at25	(TableValueType)((NtcAdcMaxVal*NtcResVal_at25 )/(NtcResVal_at25 +NtcOnBoardResVal))
			#define NtcAdcVal_at26	(TableValueType)((NtcAdcMaxVal*NtcResVal_at26 )/(NtcResVal_at26 +NtcOnBoardResVal))
			#define NtcAdcVal_at27	(TableValueType)((NtcAdcMaxVal*NtcResVal_at27 )/(NtcResVal_at27 +NtcOnBoardResVal))
			#define NtcAdcVal_at28	(TableValueType)((NtcAdcMaxVal*NtcResVal_at28 )/(NtcResVal_at28 +NtcOnBoardResVal))
			#define NtcAdcVal_at29	(TableValueType)((NtcAdcMaxVal*NtcResVal_at29 )/(NtcResVal_at29 +NtcOnBoardResVal))
			#define NtcAdcVal_at30	(TableValueType)((NtcAdcMaxVal*NtcResVal_at30 )/(NtcResVal_at30 +NtcOnBoardResVal))
			#define NtcAdcVal_at31	(TableValueType)((NtcAdcMaxVal*NtcResVal_at31 )/(NtcResVal_at31 +NtcOnBoardResVal))
			#define NtcAdcVal_at32	(TableValueType)((NtcAdcMaxVal*NtcResVal_at32 )/(NtcResVal_at32 +NtcOnBoardResVal))
			#define NtcAdcVal_at33	(TableValueType)((NtcAdcMaxVal*NtcResVal_at33 )/(NtcResVal_at33 +NtcOnBoardResVal))
			#define NtcAdcVal_at34	(TableValueType)((NtcAdcMaxVal*NtcResVal_at34 )/(NtcResVal_at34 +NtcOnBoardResVal))
			#define NtcAdcVal_at35	(TableValueType)((NtcAdcMaxVal*NtcResVal_at35 )/(NtcResVal_at35 +NtcOnBoardResVal))
			#define NtcAdcVal_at36	(TableValueType)((NtcAdcMaxVal*NtcResVal_at36 )/(NtcResVal_at36 +NtcOnBoardResVal))
			#define NtcAdcVal_at37	(TableValueType)((NtcAdcMaxVal*NtcResVal_at37 )/(NtcResVal_at37 +NtcOnBoardResVal))
			#define NtcAdcVal_at38	(TableValueType)((NtcAdcMaxVal*NtcResVal_at38 )/(NtcResVal_at38 +NtcOnBoardResVal))
			#define NtcAdcVal_at39	(TableValueType)((NtcAdcMaxVal*NtcResVal_at39 )/(NtcResVal_at39 +NtcOnBoardResVal))
			#define NtcAdcVal_at40	(TableValueType)((NtcAdcMaxVal*NtcResVal_at40 )/(NtcResVal_at40 +NtcOnBoardResVal))
			#define NtcAdcVal_at41	(TableValueType)((NtcAdcMaxVal*NtcResVal_at41 )/(NtcResVal_at41 +NtcOnBoardResVal))
			#define NtcAdcVal_at42	(TableValueType)((NtcAdcMaxVal*NtcResVal_at42 )/(NtcResVal_at42 +NtcOnBoardResVal))
			#define NtcAdcVal_at43	(TableValueType)((NtcAdcMaxVal*NtcResVal_at43 )/(NtcResVal_at43 +NtcOnBoardResVal))
			#define NtcAdcVal_at44	(TableValueType)((NtcAdcMaxVal*NtcResVal_at44 )/(NtcResVal_at44 +NtcOnBoardResVal))
			#define NtcAdcVal_at45	(TableValueType)((NtcAdcMaxVal*NtcResVal_at45 )/(NtcResVal_at45 +NtcOnBoardResVal))
			#define NtcAdcVal_at46	(TableValueType)((NtcAdcMaxVal*NtcResVal_at46 )/(NtcResVal_at46 +NtcOnBoardResVal))
			#define NtcAdcVal_at47	(TableValueType)((NtcAdcMaxVal*NtcResVal_at47 )/(NtcResVal_at47 +NtcOnBoardResVal))
			#define NtcAdcVal_at48	(TableValueType)((NtcAdcMaxVal*NtcResVal_at48 )/(NtcResVal_at48 +NtcOnBoardResVal))
			#define NtcAdcVal_at49	(TableValueType)((NtcAdcMaxVal*NtcResVal_at49 )/(NtcResVal_at49 +NtcOnBoardResVal))
			#define NtcAdcVal_at50	(TableValueType)((NtcAdcMaxVal*NtcResVal_at50 )/(NtcResVal_at50 +NtcOnBoardResVal))
			#define NtcAdcVal_at51	(TableValueType)((NtcAdcMaxVal*NtcResVal_at51 )/(NtcResVal_at51 +NtcOnBoardResVal))
			#define NtcAdcVal_at52	(TableValueType)((NtcAdcMaxVal*NtcResVal_at52 )/(NtcResVal_at52 +NtcOnBoardResVal))
			#define NtcAdcVal_at53	(TableValueType)((NtcAdcMaxVal*NtcResVal_at53 )/(NtcResVal_at53 +NtcOnBoardResVal))
			#define NtcAdcVal_at54	(TableValueType)((NtcAdcMaxVal*NtcResVal_at54 )/(NtcResVal_at54 +NtcOnBoardResVal))
			#define NtcAdcVal_at55	(TableValueType)((NtcAdcMaxVal*NtcResVal_at55 )/(NtcResVal_at55 +NtcOnBoardResVal))
			#define NtcAdcVal_at56	(TableValueType)((NtcAdcMaxVal*NtcResVal_at56 )/(NtcResVal_at56 +NtcOnBoardResVal))
			#define NtcAdcVal_at57	(TableValueType)((NtcAdcMaxVal*NtcResVal_at57 )/(NtcResVal_at57 +NtcOnBoardResVal))
			#define NtcAdcVal_at58	(TableValueType)((NtcAdcMaxVal*NtcResVal_at58 )/(NtcResVal_at58 +NtcOnBoardResVal))
			#define NtcAdcVal_at59	(TableValueType)((NtcAdcMaxVal*NtcResVal_at59 )/(NtcResVal_at59 +NtcOnBoardResVal))
			#define NtcAdcVal_at60	(TableValueType)((NtcAdcMaxVal*NtcResVal_at60 )/(NtcResVal_at60 +NtcOnBoardResVal))
			#define NtcAdcVal_at61	(TableValueType)((NtcAdcMaxVal*NtcResVal_at61 )/(NtcResVal_at61 +NtcOnBoardResVal))
			#define NtcAdcVal_at62	(TableValueType)((NtcAdcMaxVal*NtcResVal_at62 )/(NtcResVal_at62 +NtcOnBoardResVal))
			#define NtcAdcVal_at63	(TableValueType)((NtcAdcMaxVal*NtcResVal_at63 )/(NtcResVal_at63 +NtcOnBoardResVal))
			#define NtcAdcVal_at64	(TableValueType)((NtcAdcMaxVal*NtcResVal_at64 )/(NtcResVal_at64 +NtcOnBoardResVal))
			#define NtcAdcVal_at65	(TableValueType)((NtcAdcMaxVal*NtcResVal_at65 )/(NtcResVal_at65 +NtcOnBoardResVal))
			#define NtcAdcVal_at66	(TableValueType)((NtcAdcMaxVal*NtcResVal_at66 )/(NtcResVal_at66 +NtcOnBoardResVal))
			#define NtcAdcVal_at67	(TableValueType)((NtcAdcMaxVal*NtcResVal_at67 )/(NtcResVal_at67 +NtcOnBoardResVal))
			#define NtcAdcVal_at68	(TableValueType)((NtcAdcMaxVal*NtcResVal_at68 )/(NtcResVal_at68 +NtcOnBoardResVal))
			#define NtcAdcVal_at69	(TableValueType)((NtcAdcMaxVal*NtcResVal_at69 )/(NtcResVal_at69 +NtcOnBoardResVal))
			#define NtcAdcVal_at70	(TableValueType)((NtcAdcMaxVal*NtcResVal_at70 )/(NtcResVal_at70 +NtcOnBoardResVal))
			#define NtcAdcVal_at71	(TableValueType)((NtcAdcMaxVal*NtcResVal_at71 )/(NtcResVal_at71 +NtcOnBoardResVal))
			#define NtcAdcVal_at72	(TableValueType)((NtcAdcMaxVal*NtcResVal_at72 )/(NtcResVal_at72 +NtcOnBoardResVal))
			#define NtcAdcVal_at73	(TableValueType)((NtcAdcMaxVal*NtcResVal_at73 )/(NtcResVal_at73 +NtcOnBoardResVal))
			#define NtcAdcVal_at74	(TableValueType)((NtcAdcMaxVal*NtcResVal_at74 )/(NtcResVal_at74 +NtcOnBoardResVal))
			#define NtcAdcVal_at75	(TableValueType)((NtcAdcMaxVal*NtcResVal_at75 )/(NtcResVal_at75 +NtcOnBoardResVal))
			#define NtcAdcVal_at76	(TableValueType)((NtcAdcMaxVal*NtcResVal_at76 )/(NtcResVal_at76 +NtcOnBoardResVal))
			#define NtcAdcVal_at77	(TableValueType)((NtcAdcMaxVal*NtcResVal_at77 )/(NtcResVal_at77 +NtcOnBoardResVal))
			#define NtcAdcVal_at78	(TableValueType)((NtcAdcMaxVal*NtcResVal_at78 )/(NtcResVal_at78 +NtcOnBoardResVal))
			#define NtcAdcVal_at79	(TableValueType)((NtcAdcMaxVal*NtcResVal_at79 )/(NtcResVal_at79 +NtcOnBoardResVal))
			#define NtcAdcVal_at80	(TableValueType)((NtcAdcMaxVal*NtcResVal_at80 )/(NtcResVal_at80 +NtcOnBoardResVal))
			#define NtcAdcVal_at81	(TableValueType)((NtcAdcMaxVal*NtcResVal_at81 )/(NtcResVal_at81 +NtcOnBoardResVal))
			#define NtcAdcVal_at82	(TableValueType)((NtcAdcMaxVal*NtcResVal_at82 )/(NtcResVal_at82 +NtcOnBoardResVal))
			#define NtcAdcVal_at83	(TableValueType)((NtcAdcMaxVal*NtcResVal_at83 )/(NtcResVal_at83 +NtcOnBoardResVal))
			#define NtcAdcVal_at84	(TableValueType)((NtcAdcMaxVal*NtcResVal_at84 )/(NtcResVal_at84 +NtcOnBoardResVal))
			#define NtcAdcVal_at85	(TableValueType)((NtcAdcMaxVal*NtcResVal_at85 )/(NtcResVal_at85 +NtcOnBoardResVal))
			#define NtcAdcVal_at86	(TableValueType)((NtcAdcMaxVal*NtcResVal_at86 )/(NtcResVal_at86 +NtcOnBoardResVal))
			#define NtcAdcVal_at87	(TableValueType)((NtcAdcMaxVal*NtcResVal_at87 )/(NtcResVal_at87 +NtcOnBoardResVal))
			#define NtcAdcVal_at88	(TableValueType)((NtcAdcMaxVal*NtcResVal_at88 )/(NtcResVal_at88 +NtcOnBoardResVal))
			#define NtcAdcVal_at89	(TableValueType)((NtcAdcMaxVal*NtcResVal_at89 )/(NtcResVal_at89 +NtcOnBoardResVal))
			#define NtcAdcVal_at90	(TableValueType)((NtcAdcMaxVal*NtcResVal_at90 )/(NtcResVal_at90 +NtcOnBoardResVal))
			#define NtcAdcVal_at91	(TableValueType)((NtcAdcMaxVal*NtcResVal_at91 )/(NtcResVal_at91 +NtcOnBoardResVal))
			#define NtcAdcVal_at92	(TableValueType)((NtcAdcMaxVal*NtcResVal_at92 )/(NtcResVal_at92 +NtcOnBoardResVal))
			#define NtcAdcVal_at93	(TableValueType)((NtcAdcMaxVal*NtcResVal_at93 )/(NtcResVal_at93 +NtcOnBoardResVal))
			#define NtcAdcVal_at94	(TableValueType)((NtcAdcMaxVal*NtcResVal_at94 )/(NtcResVal_at94 +NtcOnBoardResVal))
			#define NtcAdcVal_at95	(TableValueType)((NtcAdcMaxVal*NtcResVal_at95 )/(NtcResVal_at95 +NtcOnBoardResVal))
			#define NtcAdcVal_at96	(TableValueType)((NtcAdcMaxVal*NtcResVal_at96 )/(NtcResVal_at96 +NtcOnBoardResVal))
			#define NtcAdcVal_at97	(TableValueType)((NtcAdcMaxVal*NtcResVal_at97 )/(NtcResVal_at97 +NtcOnBoardResVal))
			#define NtcAdcVal_at98	(TableValueType)((NtcAdcMaxVal*NtcResVal_at98 )/(NtcResVal_at98 +NtcOnBoardResVal))
			#define NtcAdcVal_at99	(TableValueType)((NtcAdcMaxVal*NtcResVal_at99 )/(NtcResVal_at99 +NtcOnBoardResVal))
			#define NtcAdcVal_at100	(TableValueType)((NtcAdcMaxVal*NtcResVal_at100)/(NtcResVal_at100+NtcOnBoardResVal))
			#define NtcAdcVal_at101	(TableValueType)((NtcAdcMaxVal*NtcResVal_at101)/(NtcResVal_at101+NtcOnBoardResVal))
			#define NtcAdcVal_at102	(TableValueType)((NtcAdcMaxVal*NtcResVal_at102)/(NtcResVal_at102+NtcOnBoardResVal))
			#define NtcAdcVal_at103	(TableValueType)((NtcAdcMaxVal*NtcResVal_at103)/(NtcResVal_at103+NtcOnBoardResVal))
			#define NtcAdcVal_at104	(TableValueType)((NtcAdcMaxVal*NtcResVal_at104)/(NtcResVal_at104+NtcOnBoardResVal))
			#define NtcAdcVal_at105	(TableValueType)((NtcAdcMaxVal*NtcResVal_at105)/(NtcResVal_at105+NtcOnBoardResVal))
			#define NtcAdcVal_at106	(TableValueType)((NtcAdcMaxVal*NtcResVal_at106)/(NtcResVal_at106+NtcOnBoardResVal))
			#define NtcAdcVal_at107	(TableValueType)((NtcAdcMaxVal*NtcResVal_at107)/(NtcResVal_at107+NtcOnBoardResVal))
			#define NtcAdcVal_at108	(TableValueType)((NtcAdcMaxVal*NtcResVal_at108)/(NtcResVal_at108+NtcOnBoardResVal))
			#define NtcAdcVal_at109	(TableValueType)((NtcAdcMaxVal*NtcResVal_at109)/(NtcResVal_at109+NtcOnBoardResVal))
			#define NtcAdcVal_at110	(TableValueType)((NtcAdcMaxVal*NtcResVal_at110)/(NtcResVal_at110+NtcOnBoardResVal))
			#define NtcAdcVal_at111	(TableValueType)((NtcAdcMaxVal*NtcResVal_at111)/(NtcResVal_at111+NtcOnBoardResVal))
			#define NtcAdcVal_at112	(TableValueType)((NtcAdcMaxVal*NtcResVal_at112)/(NtcResVal_at112+NtcOnBoardResVal))
			#define NtcAdcVal_at113	(TableValueType)((NtcAdcMaxVal*NtcResVal_at113)/(NtcResVal_at113+NtcOnBoardResVal))
			#define NtcAdcVal_at114	(TableValueType)((NtcAdcMaxVal*NtcResVal_at114)/(NtcResVal_at114+NtcOnBoardResVal))
			#define NtcAdcVal_at115	(TableValueType)((NtcAdcMaxVal*NtcResVal_at115)/(NtcResVal_at115+NtcOnBoardResVal))
			#define NtcAdcVal_at116	(TableValueType)((NtcAdcMaxVal*NtcResVal_at116)/(NtcResVal_at116+NtcOnBoardResVal))
			#define NtcAdcVal_at117	(TableValueType)((NtcAdcMaxVal*NtcResVal_at117)/(NtcResVal_at117+NtcOnBoardResVal))
			#define NtcAdcVal_at118	(TableValueType)((NtcAdcMaxVal*NtcResVal_at118)/(NtcResVal_at118+NtcOnBoardResVal))
			#define NtcAdcVal_at119	(TableValueType)((NtcAdcMaxVal*NtcResVal_at119)/(NtcResVal_at119+NtcOnBoardResVal))
			#define NtcAdcVal_at120	(TableValueType)((NtcAdcMaxVal*NtcResVal_at120)/(NtcResVal_at120+NtcOnBoardResVal))
			#define NtcAdcVal_at121	(TableValueType)((NtcAdcMaxVal*NtcResVal_at121)/(NtcResVal_at121+NtcOnBoardResVal))
			#define NtcAdcVal_at122	(TableValueType)((NtcAdcMaxVal*NtcResVal_at122)/(NtcResVal_at122+NtcOnBoardResVal))
			#define NtcAdcVal_at123	(TableValueType)((NtcAdcMaxVal*NtcResVal_at123)/(NtcResVal_at123+NtcOnBoardResVal))
			#define NtcAdcVal_at124	(TableValueType)((NtcAdcMaxVal*NtcResVal_at124)/(NtcResVal_at124+NtcOnBoardResVal))
			#define NtcAdcVal_at125	(TableValueType)((NtcAdcMaxVal*NtcResVal_at125)/(NtcResVal_at125+NtcOnBoardResVal))
			#define NtcAdcVal_at126	(TableValueType)((NtcAdcMaxVal*NtcResVal_at126)/(NtcResVal_at126+NtcOnBoardResVal))
			#define NtcAdcVal_at127	(TableValueType)((NtcAdcMaxVal*NtcResVal_at127)/(NtcResVal_at127+NtcOnBoardResVal))
			#define NtcAdcVal_at128	(TableValueType)((NtcAdcMaxVal*NtcResVal_at128)/(NtcResVal_at128+NtcOnBoardResVal))
			#define NtcAdcVal_at129	(TableValueType)((NtcAdcMaxVal*NtcResVal_at129)/(NtcResVal_at129+NtcOnBoardResVal))
			#define NtcAdcVal_at130	(TableValueType)((NtcAdcMaxVal*NtcResVal_at130)/(NtcResVal_at130+NtcOnBoardResVal))
			#define NtcAdcVal_at131	(TableValueType)((NtcAdcMaxVal*NtcResVal_at131)/(NtcResVal_at131+NtcOnBoardResVal))
			#define NtcAdcVal_at132	(TableValueType)((NtcAdcMaxVal*NtcResVal_at132)/(NtcResVal_at132+NtcOnBoardResVal))
			#define NtcAdcVal_at133	(TableValueType)((NtcAdcMaxVal*NtcResVal_at133)/(NtcResVal_at133+NtcOnBoardResVal))
			#define NtcAdcVal_at134	(TableValueType)((NtcAdcMaxVal*NtcResVal_at134)/(NtcResVal_at134+NtcOnBoardResVal))
			#define NtcAdcVal_at135	(TableValueType)((NtcAdcMaxVal*NtcResVal_at135)/(NtcResVal_at135+NtcOnBoardResVal))
			#define NtcAdcVal_at136	(TableValueType)((NtcAdcMaxVal*NtcResVal_at136)/(NtcResVal_at136+NtcOnBoardResVal))
			#define NtcAdcVal_at137	(TableValueType)((NtcAdcMaxVal*NtcResVal_at137)/(NtcResVal_at137+NtcOnBoardResVal))
			#define NtcAdcVal_at138	(TableValueType)((NtcAdcMaxVal*NtcResVal_at138)/(NtcResVal_at138+NtcOnBoardResVal))
			#define NtcAdcVal_at139	(TableValueType)((NtcAdcMaxVal*NtcResVal_at139)/(NtcResVal_at139+NtcOnBoardResVal))
			#define NtcAdcVal_at140	(TableValueType)((NtcAdcMaxVal*NtcResVal_at140)/(NtcResVal_at140+NtcOnBoardResVal))
			#define NtcAdcVal_at141	(TableValueType)((NtcAdcMaxVal*NtcResVal_at141)/(NtcResVal_at141+NtcOnBoardResVal))
			#define NtcAdcVal_at142	(TableValueType)((NtcAdcMaxVal*NtcResVal_at142)/(NtcResVal_at142+NtcOnBoardResVal))
			#define NtcAdcVal_at143	(TableValueType)((NtcAdcMaxVal*NtcResVal_at143)/(NtcResVal_at143+NtcOnBoardResVal))
			#define NtcAdcVal_at144	(TableValueType)((NtcAdcMaxVal*NtcResVal_at144)/(NtcResVal_at144+NtcOnBoardResVal))
			#define NtcAdcVal_at145	(TableValueType)((NtcAdcMaxVal*NtcResVal_at145)/(NtcResVal_at145+NtcOnBoardResVal))
			#define NtcAdcVal_at146	(TableValueType)((NtcAdcMaxVal*NtcResVal_at146)/(NtcResVal_at146+NtcOnBoardResVal))
			#define NtcAdcVal_at147	(TableValueType)((NtcAdcMaxVal*NtcResVal_at147)/(NtcResVal_at147+NtcOnBoardResVal))
			#define NtcAdcVal_at148	(TableValueType)((NtcAdcMaxVal*NtcResVal_at148)/(NtcResVal_at148+NtcOnBoardResVal))
			#define NtcAdcVal_at149	(TableValueType)((NtcAdcMaxVal*NtcResVal_at149)/(NtcResVal_at149+NtcOnBoardResVal))
			#define NtcAdcVal_at150	(TableValueType)((NtcAdcMaxVal*NtcResVal_at150)/(NtcResVal_at150+NtcOnBoardResVal))
			#define NtcAdcVal_at151	(TableValueType)((NtcAdcMaxVal*NtcResVal_at151)/(NtcResVal_at151+NtcOnBoardResVal))
			#define NtcAdcVal_at152	(TableValueType)((NtcAdcMaxVal*NtcResVal_at152)/(NtcResVal_at152+NtcOnBoardResVal))
			#define NtcAdcVal_at153	(TableValueType)((NtcAdcMaxVal*NtcResVal_at153)/(NtcResVal_at153+NtcOnBoardResVal))
			#define NtcAdcVal_at154	(TableValueType)((NtcAdcMaxVal*NtcResVal_at154)/(NtcResVal_at154+NtcOnBoardResVal))
			#define NtcAdcVal_at155	(TableValueType)((NtcAdcMaxVal*NtcResVal_at155)/(NtcResVal_at155+NtcOnBoardResVal))
			#define NtcAdcVal_at156	(TableValueType)((NtcAdcMaxVal*NtcResVal_at156)/(NtcResVal_at156+NtcOnBoardResVal))
			#define NtcAdcVal_at157	(TableValueType)((NtcAdcMaxVal*NtcResVal_at157)/(NtcResVal_at157+NtcOnBoardResVal))
			#define NtcAdcVal_at158	(TableValueType)((NtcAdcMaxVal*NtcResVal_at158)/(NtcResVal_at158+NtcOnBoardResVal))
			#define NtcAdcVal_at159	(TableValueType)((NtcAdcMaxVal*NtcResVal_at159)/(NtcResVal_at159+NtcOnBoardResVal))
			#define NtcAdcVal_at160	(TableValueType)((NtcAdcMaxVal*NtcResVal_at160)/(NtcResVal_at160+NtcOnBoardResVal))
			#define NtcAdcVal_at161	(TableValueType)((NtcAdcMaxVal*NtcResVal_at161)/(NtcResVal_at161+NtcOnBoardResVal))
			#define NtcAdcVal_at162	(TableValueType)((NtcAdcMaxVal*NtcResVal_at162)/(NtcResVal_at162+NtcOnBoardResVal))
			#define NtcAdcVal_at163	(TableValueType)((NtcAdcMaxVal*NtcResVal_at163)/(NtcResVal_at163+NtcOnBoardResVal))
			#define NtcAdcVal_at164	(TableValueType)((NtcAdcMaxVal*NtcResVal_at164)/(NtcResVal_at164+NtcOnBoardResVal))
			#define NtcAdcVal_at165	(TableValueType)((NtcAdcMaxVal*NtcResVal_at165)/(NtcResVal_at165+NtcOnBoardResVal))
			#define NtcAdcVal_at166	(TableValueType)((NtcAdcMaxVal*NtcResVal_at166)/(NtcResVal_at166+NtcOnBoardResVal))
			#define NtcAdcVal_at167	(TableValueType)((NtcAdcMaxVal*NtcResVal_at167)/(NtcResVal_at167+NtcOnBoardResVal))
			#define NtcAdcVal_at168	(TableValueType)((NtcAdcMaxVal*NtcResVal_at168)/(NtcResVal_at168+NtcOnBoardResVal))
			#define NtcAdcVal_at169	(TableValueType)((NtcAdcMaxVal*NtcResVal_at169)/(NtcResVal_at169+NtcOnBoardResVal))
			#define NtcAdcVal_at170	(TableValueType)((NtcAdcMaxVal*NtcResVal_at170)/(NtcResVal_at170+NtcOnBoardResVal))
			#define NtcAdcVal_at171	(TableValueType)((NtcAdcMaxVal*NtcResVal_at171)/(NtcResVal_at171+NtcOnBoardResVal))
			#define NtcAdcVal_at172	(TableValueType)((NtcAdcMaxVal*NtcResVal_at172)/(NtcResVal_at172+NtcOnBoardResVal))
			#define NtcAdcVal_at173	(TableValueType)((NtcAdcMaxVal*NtcResVal_at173)/(NtcResVal_at173+NtcOnBoardResVal))
			#define NtcAdcVal_at174	(TableValueType)((NtcAdcMaxVal*NtcResVal_at174)/(NtcResVal_at174+NtcOnBoardResVal))
			#define NtcAdcVal_at175	(TableValueType)((NtcAdcMaxVal*NtcResVal_at175)/(NtcResVal_at175+NtcOnBoardResVal))
			#define NtcAdcVal_at176	(TableValueType)((NtcAdcMaxVal*NtcResVal_at176)/(NtcResVal_at176+NtcOnBoardResVal))
			#define NtcAdcVal_at177	(TableValueType)((NtcAdcMaxVal*NtcResVal_at177)/(NtcResVal_at177+NtcOnBoardResVal))
			#define NtcAdcVal_at178	(TableValueType)((NtcAdcMaxVal*NtcResVal_at178)/(NtcResVal_at178+NtcOnBoardResVal))
			#define NtcAdcVal_at179	(TableValueType)((NtcAdcMaxVal*NtcResVal_at179)/(NtcResVal_at179+NtcOnBoardResVal))
			#define NtcAdcVal_at180	(TableValueType)((NtcAdcMaxVal*NtcResVal_at180)/(NtcResVal_at180+NtcOnBoardResVal))
			#define NtcAdcVal_at181	(TableValueType)((NtcAdcMaxVal*NtcResVal_at181)/(NtcResVal_at181+NtcOnBoardResVal))
			#define NtcAdcVal_at182	(TableValueType)((NtcAdcMaxVal*NtcResVal_at182)/(NtcResVal_at182+NtcOnBoardResVal))
			#define NtcAdcVal_at183	(TableValueType)((NtcAdcMaxVal*NtcResVal_at183)/(NtcResVal_at183+NtcOnBoardResVal))
			#define NtcAdcVal_at184	(TableValueType)((NtcAdcMaxVal*NtcResVal_at184)/(NtcResVal_at184+NtcOnBoardResVal))
			#define NtcAdcVal_at185	(TableValueType)((NtcAdcMaxVal*NtcResVal_at185)/(NtcResVal_at185+NtcOnBoardResVal))
			#define NtcAdcVal_at186	(TableValueType)((NtcAdcMaxVal*NtcResVal_at186)/(NtcResVal_at186+NtcOnBoardResVal))
			#define NtcAdcVal_at187	(TableValueType)((NtcAdcMaxVal*NtcResVal_at187)/(NtcResVal_at187+NtcOnBoardResVal))
			#define NtcAdcVal_at188	(TableValueType)((NtcAdcMaxVal*NtcResVal_at188)/(NtcResVal_at188+NtcOnBoardResVal))
			#define NtcAdcVal_at189	(TableValueType)((NtcAdcMaxVal*NtcResVal_at189)/(NtcResVal_at189+NtcOnBoardResVal))
			#define NtcAdcVal_at190	(TableValueType)((NtcAdcMaxVal*NtcResVal_at190)/(NtcResVal_at190+NtcOnBoardResVal))
			#define NtcAdcVal_at191	(TableValueType)((NtcAdcMaxVal*NtcResVal_at191)/(NtcResVal_at191+NtcOnBoardResVal))
			#define NtcAdcVal_at192	(TableValueType)((NtcAdcMaxVal*NtcResVal_at192)/(NtcResVal_at192+NtcOnBoardResVal))
			#define NtcAdcVal_at193	(TableValueType)((NtcAdcMaxVal*NtcResVal_at193)/(NtcResVal_at193+NtcOnBoardResVal))
			#define NtcAdcVal_at194	(TableValueType)((NtcAdcMaxVal*NtcResVal_at194)/(NtcResVal_at194+NtcOnBoardResVal))
			#define NtcAdcVal_at195	(TableValueType)((NtcAdcMaxVal*NtcResVal_at195)/(NtcResVal_at195+NtcOnBoardResVal))
			#define NtcAdcVal_at196	(TableValueType)((NtcAdcMaxVal*NtcResVal_at196)/(NtcResVal_at196+NtcOnBoardResVal))
			#define NtcAdcVal_at197	(TableValueType)((NtcAdcMaxVal*NtcResVal_at197)/(NtcResVal_at197+NtcOnBoardResVal))
			#define NtcAdcVal_at198	(TableValueType)((NtcAdcMaxVal*NtcResVal_at198)/(NtcResVal_at198+NtcOnBoardResVal))
			#define NtcAdcVal_at199	(TableValueType)((NtcAdcMaxVal*NtcResVal_at199)/(NtcResVal_at199+NtcOnBoardResVal))
			#define NtcAdcVal_at200	(TableValueType)((NtcAdcMaxVal*NtcResVal_at200)/(NtcResVal_at200+NtcOnBoardResVal))
			#define NtcAdcVal_at201	(TableValueType)((NtcAdcMaxVal*NtcResVal_at201)/(NtcResVal_at201+NtcOnBoardResVal))
			#define NtcAdcVal_at202	(TableValueType)((NtcAdcMaxVal*NtcResVal_at202)/(NtcResVal_at202+NtcOnBoardResVal))
			#define NtcAdcVal_at203	(TableValueType)((NtcAdcMaxVal*NtcResVal_at203)/(NtcResVal_at203+NtcOnBoardResVal))
			#define NtcAdcVal_at204	(TableValueType)((NtcAdcMaxVal*NtcResVal_at204)/(NtcResVal_at204+NtcOnBoardResVal))
			#define NtcAdcVal_at205	(TableValueType)((NtcAdcMaxVal*NtcResVal_at205)/(NtcResVal_at205+NtcOnBoardResVal))
			#define NtcAdcVal_at206	(TableValueType)((NtcAdcMaxVal*NtcResVal_at206)/(NtcResVal_at206+NtcOnBoardResVal))
			#define NtcAdcVal_at207	(TableValueType)((NtcAdcMaxVal*NtcResVal_at207)/(NtcResVal_at207+NtcOnBoardResVal))
			#define NtcAdcVal_at208	(TableValueType)((NtcAdcMaxVal*NtcResVal_at208)/(NtcResVal_at208+NtcOnBoardResVal))
			#define NtcAdcVal_at209	(TableValueType)((NtcAdcMaxVal*NtcResVal_at209)/(NtcResVal_at209+NtcOnBoardResVal))
			#define NtcAdcVal_at210	(TableValueType)((NtcAdcMaxVal*NtcResVal_at210)/(NtcResVal_at210+NtcOnBoardResVal))
			#define NtcAdcVal_at211	(TableValueType)((NtcAdcMaxVal*NtcResVal_at211)/(NtcResVal_at211+NtcOnBoardResVal))
			#define NtcAdcVal_at212	(TableValueType)((NtcAdcMaxVal*NtcResVal_at212)/(NtcResVal_at212+NtcOnBoardResVal))
			#define NtcAdcVal_at213	(TableValueType)((NtcAdcMaxVal*NtcResVal_at213)/(NtcResVal_at213+NtcOnBoardResVal))
			#define NtcAdcVal_at214	(TableValueType)((NtcAdcMaxVal*NtcResVal_at214)/(NtcResVal_at214+NtcOnBoardResVal))
			#define NtcAdcVal_at215	(TableValueType)((NtcAdcMaxVal*NtcResVal_at215)/(NtcResVal_at215+NtcOnBoardResVal))
			#define NtcAdcVal_at216	(TableValueType)((NtcAdcMaxVal*NtcResVal_at216)/(NtcResVal_at216+NtcOnBoardResVal))
			#define NtcAdcVal_at217	(TableValueType)((NtcAdcMaxVal*NtcResVal_at217)/(NtcResVal_at217+NtcOnBoardResVal))
			#define NtcAdcVal_at218	(TableValueType)((NtcAdcMaxVal*NtcResVal_at218)/(NtcResVal_at218+NtcOnBoardResVal))
			#define NtcAdcVal_at219	(TableValueType)((NtcAdcMaxVal*NtcResVal_at219)/(NtcResVal_at219+NtcOnBoardResVal))
			#define NtcAdcVal_at220	(TableValueType)((NtcAdcMaxVal*NtcResVal_at220)/(NtcResVal_at220+NtcOnBoardResVal))
			#define NtcAdcVal_at221	(TableValueType)((NtcAdcMaxVal*NtcResVal_at221)/(NtcResVal_at221+NtcOnBoardResVal))
			#define NtcAdcVal_at222	(TableValueType)((NtcAdcMaxVal*NtcResVal_at222)/(NtcResVal_at222+NtcOnBoardResVal))
			#define NtcAdcVal_at223	(TableValueType)((NtcAdcMaxVal*NtcResVal_at223)/(NtcResVal_at223+NtcOnBoardResVal))
			#define NtcAdcVal_at224	(TableValueType)((NtcAdcMaxVal*NtcResVal_at224)/(NtcResVal_at224+NtcOnBoardResVal))
			#define NtcAdcVal_at225	(TableValueType)((NtcAdcMaxVal*NtcResVal_at225)/(NtcResVal_at225+NtcOnBoardResVal))
			#define NtcAdcVal_at226	(TableValueType)((NtcAdcMaxVal*NtcResVal_at226)/(NtcResVal_at226+NtcOnBoardResVal))
			#define NtcAdcVal_at227	(TableValueType)((NtcAdcMaxVal*NtcResVal_at227)/(NtcResVal_at227+NtcOnBoardResVal))
			#define NtcAdcVal_at228	(TableValueType)((NtcAdcMaxVal*NtcResVal_at228)/(NtcResVal_at228+NtcOnBoardResVal))
			#define NtcAdcVal_at229	(TableValueType)((NtcAdcMaxVal*NtcResVal_at229)/(NtcResVal_at229+NtcOnBoardResVal))
			#define NtcAdcVal_at230	(TableValueType)((NtcAdcMaxVal*NtcResVal_at230)/(NtcResVal_at230+NtcOnBoardResVal))
			#define NtcAdcVal_at231	(TableValueType)((NtcAdcMaxVal*NtcResVal_at231)/(NtcResVal_at231+NtcOnBoardResVal))
			#define NtcAdcVal_at232	(TableValueType)((NtcAdcMaxVal*NtcResVal_at232)/(NtcResVal_at232+NtcOnBoardResVal))
			#define NtcAdcVal_at233	(TableValueType)((NtcAdcMaxVal*NtcResVal_at233)/(NtcResVal_at233+NtcOnBoardResVal))
			#define NtcAdcVal_at234	(TableValueType)((NtcAdcMaxVal*NtcResVal_at234)/(NtcResVal_at234+NtcOnBoardResVal))
			#define NtcAdcVal_at235	(TableValueType)((NtcAdcMaxVal*NtcResVal_at235)/(NtcResVal_at235+NtcOnBoardResVal))
			#define NtcAdcVal_at236	(TableValueType)((NtcAdcMaxVal*NtcResVal_at236)/(NtcResVal_at236+NtcOnBoardResVal))
			#define NtcAdcVal_at237	(TableValueType)((NtcAdcMaxVal*NtcResVal_at237)/(NtcResVal_at237+NtcOnBoardResVal))
			#define NtcAdcVal_at238	(TableValueType)((NtcAdcMaxVal*NtcResVal_at238)/(NtcResVal_at238+NtcOnBoardResVal))
			#define NtcAdcVal_at239	(TableValueType)((NtcAdcMaxVal*NtcResVal_at239)/(NtcResVal_at239+NtcOnBoardResVal))
			#define NtcAdcVal_at240	(TableValueType)((NtcAdcMaxVal*NtcResVal_at240)/(NtcResVal_at240+NtcOnBoardResVal))
			#define NtcAdcVal_at241	(TableValueType)((NtcAdcMaxVal*NtcResVal_at241)/(NtcResVal_at241+NtcOnBoardResVal))
			#define NtcAdcVal_at242	(TableValueType)((NtcAdcMaxVal*NtcResVal_at242)/(NtcResVal_at242+NtcOnBoardResVal))
			#define NtcAdcVal_at243	(TableValueType)((NtcAdcMaxVal*NtcResVal_at243)/(NtcResVal_at243+NtcOnBoardResVal))
			#define NtcAdcVal_at244	(TableValueType)((NtcAdcMaxVal*NtcResVal_at244)/(NtcResVal_at244+NtcOnBoardResVal))
			#define NtcAdcVal_at245	(TableValueType)((NtcAdcMaxVal*NtcResVal_at245)/(NtcResVal_at245+NtcOnBoardResVal))
			#define NtcAdcVal_at246	(TableValueType)((NtcAdcMaxVal*NtcResVal_at246)/(NtcResVal_at246+NtcOnBoardResVal))
			#define NtcAdcVal_at247	(TableValueType)((NtcAdcMaxVal*NtcResVal_at247)/(NtcResVal_at247+NtcOnBoardResVal))
			#define NtcAdcVal_at248	(TableValueType)((NtcAdcMaxVal*NtcResVal_at248)/(NtcResVal_at248+NtcOnBoardResVal))
			#define NtcAdcVal_at249	(TableValueType)((NtcAdcMaxVal*NtcResVal_at249)/(NtcResVal_at249+NtcOnBoardResVal))
			#define NtcAdcVal_at250	(TableValueType)((NtcAdcMaxVal*NtcResVal_at250)/(NtcResVal_at250+NtcOnBoardResVal))
			#define NtcAdcVal_at251	(TableValueType)((NtcAdcMaxVal*NtcResVal_at251)/(NtcResVal_at251+NtcOnBoardResVal))
			#define NtcAdcVal_at252	(TableValueType)((NtcAdcMaxVal*NtcResVal_at252)/(NtcResVal_at252+NtcOnBoardResVal))
			#define NtcAdcVal_at253	(TableValueType)((NtcAdcMaxVal*NtcResVal_at253)/(NtcResVal_at253+NtcOnBoardResVal))
			#define NtcAdcVal_at254	(TableValueType)((NtcAdcMaxVal*NtcResVal_at254)/(NtcResVal_at254+NtcOnBoardResVal))
			#define NtcAdcVal_at255	(TableValueType)((NtcAdcMaxVal*NtcResVal_at255)/(NtcResVal_at255+NtcOnBoardResVal))

		#elif (NtcOnBoardResPullType==NtcOnBoardResPullDown)

			#define NtcAdcVal_at0	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at0  +NtcOnBoardResVal))
			#define NtcAdcVal_at1	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at1  +NtcOnBoardResVal))
			#define NtcAdcVal_at2	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at2  +NtcOnBoardResVal))
			#define NtcAdcVal_at3	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at3  +NtcOnBoardResVal))
			#define NtcAdcVal_at4	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at4  +NtcOnBoardResVal))
			#define NtcAdcVal_at5	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at5  +NtcOnBoardResVal))
			#define NtcAdcVal_at6	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at6  +NtcOnBoardResVal))
			#define NtcAdcVal_at7	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at7  +NtcOnBoardResVal))
			#define NtcAdcVal_at8	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at8  +NtcOnBoardResVal))
			#define NtcAdcVal_at9	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at9  +NtcOnBoardResVal))
			#define NtcAdcVal_at10	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at10 +NtcOnBoardResVal))
			#define NtcAdcVal_at11	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at11 +NtcOnBoardResVal))
			#define NtcAdcVal_at12	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at12 +NtcOnBoardResVal))
			#define NtcAdcVal_at13	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at13 +NtcOnBoardResVal))
			#define NtcAdcVal_at14	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at14 +NtcOnBoardResVal))
			#define NtcAdcVal_at15	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at15 +NtcOnBoardResVal))
			#define NtcAdcVal_at16	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at16 +NtcOnBoardResVal))
			#define NtcAdcVal_at17	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at17 +NtcOnBoardResVal))
			#define NtcAdcVal_at18	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at18 +NtcOnBoardResVal))
			#define NtcAdcVal_at19	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at19 +NtcOnBoardResVal))
			#define NtcAdcVal_at20	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at20 +NtcOnBoardResVal))
			#define NtcAdcVal_at21	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at21 +NtcOnBoardResVal))
			#define NtcAdcVal_at22	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at22 +NtcOnBoardResVal))
			#define NtcAdcVal_at23	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at23 +NtcOnBoardResVal))
			#define NtcAdcVal_at24	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at24 +NtcOnBoardResVal))
			#define NtcAdcVal_at25	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at25 +NtcOnBoardResVal))
			#define NtcAdcVal_at26	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at26 +NtcOnBoardResVal))
			#define NtcAdcVal_at27	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at27 +NtcOnBoardResVal))
			#define NtcAdcVal_at28	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at28 +NtcOnBoardResVal))
			#define NtcAdcVal_at29	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at29 +NtcOnBoardResVal))
			#define NtcAdcVal_at30	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at30 +NtcOnBoardResVal))
			#define NtcAdcVal_at31	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at31 +NtcOnBoardResVal))
			#define NtcAdcVal_at32	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at32 +NtcOnBoardResVal))
			#define NtcAdcVal_at33	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at33 +NtcOnBoardResVal))
			#define NtcAdcVal_at34	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at34 +NtcOnBoardResVal))
			#define NtcAdcVal_at35	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at35 +NtcOnBoardResVal))
			#define NtcAdcVal_at36	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at36 +NtcOnBoardResVal))
			#define NtcAdcVal_at37	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at37 +NtcOnBoardResVal))
			#define NtcAdcVal_at38	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at38 +NtcOnBoardResVal))
			#define NtcAdcVal_at39	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at39 +NtcOnBoardResVal))
			#define NtcAdcVal_at40	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at40 +NtcOnBoardResVal))
			#define NtcAdcVal_at41	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at41 +NtcOnBoardResVal))
			#define NtcAdcVal_at42	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at42 +NtcOnBoardResVal))
			#define NtcAdcVal_at43	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at43 +NtcOnBoardResVal))
			#define NtcAdcVal_at44	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at44 +NtcOnBoardResVal))
			#define NtcAdcVal_at45	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at45 +NtcOnBoardResVal))
			#define NtcAdcVal_at46	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at46 +NtcOnBoardResVal))
			#define NtcAdcVal_at47	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at47 +NtcOnBoardResVal))
			#define NtcAdcVal_at48	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at48 +NtcOnBoardResVal))
			#define NtcAdcVal_at49	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at49 +NtcOnBoardResVal))
			#define NtcAdcVal_at50	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at50 +NtcOnBoardResVal))
			#define NtcAdcVal_at51	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at51 +NtcOnBoardResVal))
			#define NtcAdcVal_at52	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at52 +NtcOnBoardResVal))
			#define NtcAdcVal_at53	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at53 +NtcOnBoardResVal))
			#define NtcAdcVal_at54	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at54 +NtcOnBoardResVal))
			#define NtcAdcVal_at55	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at55 +NtcOnBoardResVal))
			#define NtcAdcVal_at56	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at56 +NtcOnBoardResVal))
			#define NtcAdcVal_at57	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at57 +NtcOnBoardResVal))
			#define NtcAdcVal_at58	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at58 +NtcOnBoardResVal))
			#define NtcAdcVal_at59	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at59 +NtcOnBoardResVal))
			#define NtcAdcVal_at60	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at60 +NtcOnBoardResVal))
			#define NtcAdcVal_at61	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at61 +NtcOnBoardResVal))
			#define NtcAdcVal_at62	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at62 +NtcOnBoardResVal))
			#define NtcAdcVal_at63	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at63 +NtcOnBoardResVal))
			#define NtcAdcVal_at64	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at64 +NtcOnBoardResVal))
			#define NtcAdcVal_at65	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at65 +NtcOnBoardResVal))
			#define NtcAdcVal_at66	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at66 +NtcOnBoardResVal))
			#define NtcAdcVal_at67	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at67 +NtcOnBoardResVal))
			#define NtcAdcVal_at68	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at68 +NtcOnBoardResVal))
			#define NtcAdcVal_at69	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at69 +NtcOnBoardResVal))
			#define NtcAdcVal_at70	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at70 +NtcOnBoardResVal))
			#define NtcAdcVal_at71	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at71 +NtcOnBoardResVal))
			#define NtcAdcVal_at72	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at72 +NtcOnBoardResVal))
			#define NtcAdcVal_at73	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at73 +NtcOnBoardResVal))
			#define NtcAdcVal_at74	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at74 +NtcOnBoardResVal))
			#define NtcAdcVal_at75	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at75 +NtcOnBoardResVal))
			#define NtcAdcVal_at76	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at76 +NtcOnBoardResVal))
			#define NtcAdcVal_at77	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at77 +NtcOnBoardResVal))
			#define NtcAdcVal_at78	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at78 +NtcOnBoardResVal))
			#define NtcAdcVal_at79	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at79 +NtcOnBoardResVal))
			#define NtcAdcVal_at80	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at80 +NtcOnBoardResVal))
			#define NtcAdcVal_at81	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at81 +NtcOnBoardResVal))
			#define NtcAdcVal_at82	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at82 +NtcOnBoardResVal))
			#define NtcAdcVal_at83	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at83 +NtcOnBoardResVal))
			#define NtcAdcVal_at84	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at84 +NtcOnBoardResVal))
			#define NtcAdcVal_at85	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at85 +NtcOnBoardResVal))
			#define NtcAdcVal_at86	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at86 +NtcOnBoardResVal))
			#define NtcAdcVal_at87	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at87 +NtcOnBoardResVal))
			#define NtcAdcVal_at88	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at88 +NtcOnBoardResVal))
			#define NtcAdcVal_at89	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at89 +NtcOnBoardResVal))
			#define NtcAdcVal_at90	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at90 +NtcOnBoardResVal))
			#define NtcAdcVal_at91	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at91 +NtcOnBoardResVal))
			#define NtcAdcVal_at92	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at92 +NtcOnBoardResVal))
			#define NtcAdcVal_at93	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at93 +NtcOnBoardResVal))
			#define NtcAdcVal_at94	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at94 +NtcOnBoardResVal))
			#define NtcAdcVal_at95	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at95 +NtcOnBoardResVal))
			#define NtcAdcVal_at96	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at96 +NtcOnBoardResVal))
			#define NtcAdcVal_at97	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at97 +NtcOnBoardResVal))
			#define NtcAdcVal_at98	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at98 +NtcOnBoardResVal))
			#define NtcAdcVal_at99	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at99 +NtcOnBoardResVal))
			#define NtcAdcVal_at100	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at100+NtcOnBoardResVal))
			#define NtcAdcVal_at101	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at101+NtcOnBoardResVal))
			#define NtcAdcVal_at102	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at102+NtcOnBoardResVal))
			#define NtcAdcVal_at103	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at103+NtcOnBoardResVal))
			#define NtcAdcVal_at104	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at104+NtcOnBoardResVal))
			#define NtcAdcVal_at105	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at105+NtcOnBoardResVal))
			#define NtcAdcVal_at106	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at106+NtcOnBoardResVal))
			#define NtcAdcVal_at107	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at107+NtcOnBoardResVal))
			#define NtcAdcVal_at108	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at108+NtcOnBoardResVal))
			#define NtcAdcVal_at109	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at109+NtcOnBoardResVal))
			#define NtcAdcVal_at110	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at110+NtcOnBoardResVal))
			#define NtcAdcVal_at111	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at111+NtcOnBoardResVal))
			#define NtcAdcVal_at112	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at112+NtcOnBoardResVal))
			#define NtcAdcVal_at113	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at113+NtcOnBoardResVal))
			#define NtcAdcVal_at114	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at114+NtcOnBoardResVal))
			#define NtcAdcVal_at115	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at115+NtcOnBoardResVal))
			#define NtcAdcVal_at116	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at116+NtcOnBoardResVal))
			#define NtcAdcVal_at117	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at117+NtcOnBoardResVal))
			#define NtcAdcVal_at118	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at118+NtcOnBoardResVal))
			#define NtcAdcVal_at119	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at119+NtcOnBoardResVal))
			#define NtcAdcVal_at120	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at120+NtcOnBoardResVal))
			#define NtcAdcVal_at121	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at121+NtcOnBoardResVal))
			#define NtcAdcVal_at122	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at122+NtcOnBoardResVal))
			#define NtcAdcVal_at123	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at123+NtcOnBoardResVal))
			#define NtcAdcVal_at124	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at124+NtcOnBoardResVal))
			#define NtcAdcVal_at125	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at125+NtcOnBoardResVal))
			#define NtcAdcVal_at126	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at126+NtcOnBoardResVal))
			#define NtcAdcVal_at127	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at127+NtcOnBoardResVal))
			#define NtcAdcVal_at128	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at128+NtcOnBoardResVal))
			#define NtcAdcVal_at129	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at129+NtcOnBoardResVal))
			#define NtcAdcVal_at130	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at130+NtcOnBoardResVal))
			#define NtcAdcVal_at131	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at131+NtcOnBoardResVal))
			#define NtcAdcVal_at132	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at132+NtcOnBoardResVal))
			#define NtcAdcVal_at133	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at133+NtcOnBoardResVal))
			#define NtcAdcVal_at134	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at134+NtcOnBoardResVal))
			#define NtcAdcVal_at135	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at135+NtcOnBoardResVal))
			#define NtcAdcVal_at136	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at136+NtcOnBoardResVal))
			#define NtcAdcVal_at137	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at137+NtcOnBoardResVal))
			#define NtcAdcVal_at138	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at138+NtcOnBoardResVal))
			#define NtcAdcVal_at139	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at139+NtcOnBoardResVal))
			#define NtcAdcVal_at140	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at140+NtcOnBoardResVal))
			#define NtcAdcVal_at141	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at141+NtcOnBoardResVal))
			#define NtcAdcVal_at142	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at142+NtcOnBoardResVal))
			#define NtcAdcVal_at143	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at143+NtcOnBoardResVal))
			#define NtcAdcVal_at144	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at144+NtcOnBoardResVal))
			#define NtcAdcVal_at145	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at145+NtcOnBoardResVal))
			#define NtcAdcVal_at146	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at146+NtcOnBoardResVal))
			#define NtcAdcVal_at147	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at147+NtcOnBoardResVal))
			#define NtcAdcVal_at148	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at148+NtcOnBoardResVal))
			#define NtcAdcVal_at149	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at149+NtcOnBoardResVal))
			#define NtcAdcVal_at150	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at150+NtcOnBoardResVal))
			#define NtcAdcVal_at151	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at151+NtcOnBoardResVal))
			#define NtcAdcVal_at152	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at152+NtcOnBoardResVal))
			#define NtcAdcVal_at153	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at153+NtcOnBoardResVal))
			#define NtcAdcVal_at154	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at154+NtcOnBoardResVal))
			#define NtcAdcVal_at155	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at155+NtcOnBoardResVal))
			#define NtcAdcVal_at156	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at156+NtcOnBoardResVal))
			#define NtcAdcVal_at157	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at157+NtcOnBoardResVal))
			#define NtcAdcVal_at158	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at158+NtcOnBoardResVal))
			#define NtcAdcVal_at159	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at159+NtcOnBoardResVal))
			#define NtcAdcVal_at160	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at160+NtcOnBoardResVal))
			#define NtcAdcVal_at161	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at161+NtcOnBoardResVal))
			#define NtcAdcVal_at162	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at162+NtcOnBoardResVal))
			#define NtcAdcVal_at163	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at163+NtcOnBoardResVal))
			#define NtcAdcVal_at164	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at164+NtcOnBoardResVal))
			#define NtcAdcVal_at165	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at165+NtcOnBoardResVal))
			#define NtcAdcVal_at166	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at166+NtcOnBoardResVal))
			#define NtcAdcVal_at167	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at167+NtcOnBoardResVal))
			#define NtcAdcVal_at168	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at168+NtcOnBoardResVal))
			#define NtcAdcVal_at169	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at169+NtcOnBoardResVal))
			#define NtcAdcVal_at170	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at170+NtcOnBoardResVal))
			#define NtcAdcVal_at171	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at171+NtcOnBoardResVal))
			#define NtcAdcVal_at172	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at172+NtcOnBoardResVal))
			#define NtcAdcVal_at173	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at173+NtcOnBoardResVal))
			#define NtcAdcVal_at174	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at174+NtcOnBoardResVal))
			#define NtcAdcVal_at175	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at175+NtcOnBoardResVal))
			#define NtcAdcVal_at176	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at176+NtcOnBoardResVal))
			#define NtcAdcVal_at177	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at177+NtcOnBoardResVal))
			#define NtcAdcVal_at178	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at178+NtcOnBoardResVal))
			#define NtcAdcVal_at179	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at179+NtcOnBoardResVal))
			#define NtcAdcVal_at180	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at180+NtcOnBoardResVal))
			#define NtcAdcVal_at181	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at181+NtcOnBoardResVal))
			#define NtcAdcVal_at182	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at182+NtcOnBoardResVal))
			#define NtcAdcVal_at183	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at183+NtcOnBoardResVal))
			#define NtcAdcVal_at184	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at184+NtcOnBoardResVal))
			#define NtcAdcVal_at185	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at185+NtcOnBoardResVal))
			#define NtcAdcVal_at186	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at186+NtcOnBoardResVal))
			#define NtcAdcVal_at187	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at187+NtcOnBoardResVal))
			#define NtcAdcVal_at188	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at188+NtcOnBoardResVal))
			#define NtcAdcVal_at189	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at189+NtcOnBoardResVal))
			#define NtcAdcVal_at190	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at190+NtcOnBoardResVal))
			#define NtcAdcVal_at191	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at191+NtcOnBoardResVal))
			#define NtcAdcVal_at192	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at192+NtcOnBoardResVal))
			#define NtcAdcVal_at193	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at193+NtcOnBoardResVal))
			#define NtcAdcVal_at194	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at194+NtcOnBoardResVal))
			#define NtcAdcVal_at195	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at195+NtcOnBoardResVal))
			#define NtcAdcVal_at196	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at196+NtcOnBoardResVal))
			#define NtcAdcVal_at197	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at197+NtcOnBoardResVal))
			#define NtcAdcVal_at198	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at198+NtcOnBoardResVal))
			#define NtcAdcVal_at199	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at199+NtcOnBoardResVal))
			#define NtcAdcVal_at200	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at200+NtcOnBoardResVal))
			#define NtcAdcVal_at201	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at201+NtcOnBoardResVal))
			#define NtcAdcVal_at202	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at202+NtcOnBoardResVal))
			#define NtcAdcVal_at203	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at203+NtcOnBoardResVal))
			#define NtcAdcVal_at204	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at204+NtcOnBoardResVal))
			#define NtcAdcVal_at205	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at205+NtcOnBoardResVal))
			#define NtcAdcVal_at206	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at206+NtcOnBoardResVal))
			#define NtcAdcVal_at207	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at207+NtcOnBoardResVal))
			#define NtcAdcVal_at208	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at208+NtcOnBoardResVal))
			#define NtcAdcVal_at209	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at209+NtcOnBoardResVal))
			#define NtcAdcVal_at210	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at210+NtcOnBoardResVal))
			#define NtcAdcVal_at211	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at211+NtcOnBoardResVal))
			#define NtcAdcVal_at212	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at212+NtcOnBoardResVal))
			#define NtcAdcVal_at213	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at213+NtcOnBoardResVal))
			#define NtcAdcVal_at214	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at214+NtcOnBoardResVal))
			#define NtcAdcVal_at215	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at215+NtcOnBoardResVal))
			#define NtcAdcVal_at216	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at216+NtcOnBoardResVal))
			#define NtcAdcVal_at217	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at217+NtcOnBoardResVal))
			#define NtcAdcVal_at218	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at218+NtcOnBoardResVal))
			#define NtcAdcVal_at219	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at219+NtcOnBoardResVal))
			#define NtcAdcVal_at220	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at220+NtcOnBoardResVal))
			#define NtcAdcVal_at221	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at221+NtcOnBoardResVal))
			#define NtcAdcVal_at222	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at222+NtcOnBoardResVal))
			#define NtcAdcVal_at223	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at223+NtcOnBoardResVal))
			#define NtcAdcVal_at224	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at224+NtcOnBoardResVal))
			#define NtcAdcVal_at225	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at225+NtcOnBoardResVal))
			#define NtcAdcVal_at226	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at226+NtcOnBoardResVal))
			#define NtcAdcVal_at227	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at227+NtcOnBoardResVal))
			#define NtcAdcVal_at228	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at228+NtcOnBoardResVal))
			#define NtcAdcVal_at229	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at229+NtcOnBoardResVal))
			#define NtcAdcVal_at230	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at230+NtcOnBoardResVal))
			#define NtcAdcVal_at231	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at231+NtcOnBoardResVal))
			#define NtcAdcVal_at232	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at232+NtcOnBoardResVal))
			#define NtcAdcVal_at233	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at233+NtcOnBoardResVal))
			#define NtcAdcVal_at234	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at234+NtcOnBoardResVal))
			#define NtcAdcVal_at235	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at235+NtcOnBoardResVal))
			#define NtcAdcVal_at236	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at236+NtcOnBoardResVal))
			#define NtcAdcVal_at237	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at237+NtcOnBoardResVal))
			#define NtcAdcVal_at238	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at238+NtcOnBoardResVal))
			#define NtcAdcVal_at239	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at239+NtcOnBoardResVal))
			#define NtcAdcVal_at240	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at240+NtcOnBoardResVal))
			#define NtcAdcVal_at241	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at241+NtcOnBoardResVal))
			#define NtcAdcVal_at242	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at242+NtcOnBoardResVal))
			#define NtcAdcVal_at243	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at243+NtcOnBoardResVal))
			#define NtcAdcVal_at244	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at244+NtcOnBoardResVal))
			#define NtcAdcVal_at245	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at245+NtcOnBoardResVal))
			#define NtcAdcVal_at246	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at246+NtcOnBoardResVal))
			#define NtcAdcVal_at247	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at247+NtcOnBoardResVal))
			#define NtcAdcVal_at248	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at248+NtcOnBoardResVal))
			#define NtcAdcVal_at249	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at249+NtcOnBoardResVal))
			#define NtcAdcVal_at250	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at250+NtcOnBoardResVal))
			#define NtcAdcVal_at251	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at251+NtcOnBoardResVal))
			#define NtcAdcVal_at252	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at252+NtcOnBoardResVal))
			#define NtcAdcVal_at253	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at253+NtcOnBoardResVal))
			#define NtcAdcVal_at254	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at254+NtcOnBoardResVal))
			#define NtcAdcVal_at255	(TableValueType)((NtcAdcMaxVal*NtcOnBoardResVal)/(NtcResVal_at255+NtcOnBoardResVal))
		#endif

	#endif






#endif

